/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as St25RouteImport } from './routes/st25'
import { Route as WholesaleRouteImport } from './routes/wholesale'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const St25Route = St25RouteImport.update({
  id: '/st25',
  path: '/st25',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesaleRoute = WholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certificates': typeof CertificatesRoute
  '/faq': typeof FaqRoute
  '/products': typeof ProductsRoute
  '/st25': typeof St25Route
  '/wholesale': typeof WholesaleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certificates': typeof CertificatesRoute
  '/faq': typeof FaqRoute
  '/products': typeof ProductsRoute
  '/st25': typeof St25Route
  '/wholesale': typeof WholesaleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certificates': typeof CertificatesRoute
  '/faq': typeof FaqRoute
  '/products': typeof ProductsRoute
  '/st25': typeof St25Route
  '/wholesale': typeof WholesaleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/certificates'
    | '/faq'
    | '/products'
    | '/st25'
    | '/wholesale'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/certificates'
    | '/faq'
    | '/products'
    | '/st25'
    | '/wholesale'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/certificates'
    | '/faq'
    | '/products'
    | '/st25'
    | '/wholesale'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CertificatesRoute: typeof CertificatesRoute
  FaqRoute: typeof FaqRoute
  ProductsRoute: typeof ProductsRoute
  St25Route: typeof St25Route
  WholesaleRoute: typeof WholesaleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/st25': {
      id: '/st25'
      path: '/st25'
      fullPath: '/st25'
      preLoaderRoute: typeof St25RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesale': {
      id: '/wholesale'
      path: '/wholesale'
      fullPath: '/wholesale'
      preLoaderRoute: typeof WholesaleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CertificatesRoute: CertificatesRoute,
  FaqRoute: FaqRoute,
  ProductsRoute: ProductsRoute,
  St25Route: St25Route,
  WholesaleRoute: WholesaleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
